[package]
name = "crashflow"
version = "0.1.0"
authors = ["richinseattle <richinseattle@gmail.com>"]
edition = "2018"

[dependencies]
#lazy_static = "1.2.0"
byteorder = "1.3.0"
memmap = "0.7.0"
protobuf = "2.2.2"
capstone = "0.5.0"